# PvPRanker configuration file.
---
# Database configuration. MySQL is required to use this plugin.
db:
  # MySQL Username
  user: root
  # MySQL Password (Remove line if you don't have one)
  pass: pass
  # Host (probably don't need to change)
  host: localhost
  # Port (also don't need to change)
  port: 3306
  # Database name
  name: mydb

# The kill ranks.
# The rank with the lowest score is the minimum score allowed.
ranks:
  feeder:
    # The name of the rank. You can use chat colors here.
    name: Feeder
    # The minimum score needed to have this rank.
    score: -100
    worth: 1
  bungler:
    name: Bungler
    score: -50
    worth: 1
  noob:
    name: Noob
    score: -20
    worth: 1
  recruit:
    name: Recruit
    score: -5
    worth: 1
  novice:
    name: Novice
    score: 1
    worth: 1
  apprentice:
    name: Apprentice
    score: 10
    worth: 2
  journeyman:
    name: Journeyman
    score: 50
    worth: 2
  adept:
    name: Adept
    score: 100
    worth: 5
  master:
    name: Master
    score: 200
    worth: 10
  godlike:
    name: Godlike
    score: 500
    worth: 20
  legendary:
    name: Legendary
    score: 1000
    worth: 50
