# PvPRanker configuration file.
---
# Database configuration. MySQL is required to use this plugin.
db:
  # MySQL Username
  user: root
  # MySQL Password (Remove line if you don't have one)
  pass: pass
  # Host (probably don't need to change)
  host: localhost
  # Port (also don't need to change)
  port: 3306
  # Database name
  name: mydb

# The kill ranks.
# The rank with the lowest score will cover any score under it.
ranks:
  feeder:
    # The name of the rank. You can use chat colors here.
    name: Feeder
    # The minimum score needed to have this rank.
    score: -1000000
  noob:
    name: Noob
    score: -100
  novice:
    name: Novice
    score: 10
  apprentice:
    name: Apprentice
    score: 50
  journeyman:
    name: Journeyman
    score: 100
  adept:
    name: Adept
    score: 200
  godlike:
    name: Godlike
    score: 500
  legendary:
    name: Legendary
    score: 1000
