# PvPRanker configuration file.
---
# The current milestone.
milestone: default

# The maximum number of times a player can kill another player in a day.
max-kills-per-day: 10

# The kill ranks.
# The rank with the lowest score is the minimum score allowed.
ranks:
  feeder:
    # The name of the rank. You can use chat colors here.
    name: '&7Feeder'
    # The minimum score needed to have this rank.
    score: -1000
    worth: 1
  bungler:
    name: '&8Bungler'
    score: -500
    worth: 2
  noob:
    name: '&3Noob'
    score: -200
    worth: 5
  recruit:
    name: '&bRecruit'
    score: -50
    worth: 8
  novice:
    name: '&9Novice'
    score: 10
    worth: 10
  apprentice:
    name: '&6Apprentice'
    score: 100
    worth: 20
  journeyman:
    name: '&bJ&6o&bu&6r&bn&6e&by&6m&ba&6n'
    score: 500
    worth: 30
  adept:
    name: '&4Adept'
    score: 1000
    worth: 50
  master:
    name: '&4M&ea&4s&et&4e&er'
    score: 2000
    worth: 100
  godlike:
    name: '&4&lGOD&e&lLIKE&r'
    score: 5000
    worth: 200
  legendary:
    name: '&a&lL&b&lE&c&lG&d&lE&e&lN&d&lD&c&lA&b&lR&a&lY&r'
    score: 10000
    worth: 500
