# PvPRanker configuration file.
---
# Database configuration. MySQL is required to use this plugin.
db:
  # MySQL Username
  user: root
  # MySQL Password (Remove line if you don't have one)
  pass: pass
  # Host (probably don't need to change)
  host: localhost
  # Port (also don't need to change)
  port: 3306
  # Database name
  name: mydb

# The kill ranks.
# The rank with the lowest score is the minimum score allowed.
ranks:
  feeder:
    # The name of the rank. You can use chat colors here.
    name: '&7Feeder'
    # The minimum score needed to have this rank.
    score: -100
    worth: 1
  bungler:
    name: '&8Bungler'
    score: -50
    worth: 1
  noob:
    name: '&3Noob'
    score: -20
    worth: 1
  recruit:
    name: '&bRecruit'
    score: -5
    worth: 1
  novice:
    name: '&9Novice'
    score: 1
    worth: 1
  apprentice:
    name: '&6Apprentice'
    score: 10
    worth: 2
  journeyman:
    name: '&bJ&6o&bu&6r&bn&6e&by&6m&ba&6n'
    score: 50
    worth: 2
  adept:
    name: '&4Adept'
    score: 100
    worth: 5
  master:
    name: '&4M&ea&4s&et&4e&er'
    score: 200
    worth: 10
  godlike:
    name: '&l&4GOD&eLIKE&r'
    score: 500
    worth: 20
  legendary:
    name: '&l&aL&be&cg&de&en&dd&ca&br&ay&r'
    score: 1000
    worth: 50
