# PvPRanker configuration file.
---
# Database configuration. MySQL is required to use this plugin.
db:
  # MySQL Username
  user: root
  # MySQL Password (Remove line if you don't have one)
  pass: pass
  # Host (probably don't need to change)
  host: localhost
  # Port (also don't need to change)
  port: 3306
  # Database name
  name: mydb

# The amount of score to transfer when a player is killed.
# If the player killed's score multiplied by this number is greater than
# killValue, then that many points will be transferred instead.
# Set this number to 0 if you want to disable this.
kill-multiplier: 0.2

# The minimum amount of points to transfer when a player is killed.
kill-value: 10

# The kill ranks.
# The rank with the lowest score will cover any score under it.
ranks:
  feeder:
    # The name of the rank. You can use chat colors here.
    name: Feeder
    # The minimum score needed to have this rank.
    score: -1000000
  noob:
    name: Noob
    score: -100
  apprentice:
    name: Apprentice
    score: 10
  journeyman:
    name: Journeyman
    score: 50
  adept:
    name: Adept
    score: 200
  champion:
    name: Champion
    score: 500
  hero:
    name: Hero
    score: 1000
  godlike:
    name: Godlike
    score: 5000
  legendary:
    name: Legendary
    score: 10000
