name: ${project.name}
description: ${project.description}
version: ${project.version}-b${buildNumber}
author: AlbireoX
website: ${project.url}

main: ${mainClass}
depend: [EasyDB, Factions, Vault]

commands:
    pvpmilestone:
        description: Sets the milestone of the server.
        usage: 'Usage: /pvpmilestone <milestone>'
        permission: pvpranker.*
        permission-message: You are not allowed to use this command.
    pvpstats:
        description: Shows the PvP statistics of a player.
        usage: 'Usage: /pvpstats [player]'
    pvptop:
        description: Lists the top PvPers on the server.
        usage: 'Usage: /pvptop [milestone]'

permissions:
    pvpranker.*:
        description: PvPRanker admin permission

