name: PvPRanker
version: 1.0
description: Ranks people based on how good they are in PvP.
author: AlbireoX
website: http://www.new-liberty.net/

main: net.new_liberty.pvpranker.PvPRanker

commands:
    pvpmilestone:
        description: Sets the milestone of the server.
        usage: '&cUsage: /pvpmilestone <milestone>'
        permission: pvpranker.*
        permission-message: You are not allowed to use this command.
    pvpstats:
        description: Shows the PvP statistics of a player.
        usage: '&cUsage: /pvpstats [player]'
    pvptop:
        description: Lists the top PvPers on the server.
        usage: '&cUsage: /pvptop [milestone]'

permissions:
    pvpranker.*:
        description: PvPRanker admin permission

